version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run:
          command: echo Hello, World! > ~/Downloads/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - ~/Downloads/output.txt
  
  print_output:
    docker:
      - image: cimg/base:2022.03
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: cat ~/Downloads/output.txt

workflows:
  printing_the_chached_file:
    jobs:
      - save_hello_world_output
      - print_output:
          requires:
            - save_hello_world_output

