version: 2.1

commands:

  print_pipeline_id:
    description: "This Command will only fetch the workflow ID and send it to another job"
    parameters:
        to:
          type: string
          default: ${CIRCLE_WORKFLOW_ID}
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  
  print_workflow_id:
    docker:
      - image: cimg/base:2022.03
    steps:
      - print_pipeline_id

workflows:
  workflow_id_job:
    jobs:
      - print_workflow_id