version: 2.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save-hello-world-output:
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base2020.01
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Save Hello, World"
          command: "echo Hello, World! > output.txt"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - /temp.txt
            
  print-output:
    docker:
      - image: cimg/base2020.01
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Restore Hello World!"
          command: "cat output.txt"

workflows:
  printing-the-chached-file:
    jobs:
      - save-hello-world-output
      - print-output:
          requires:
            - save-hello-world-output

