version: 2.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  print-hello:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello,"

  print-world:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:13.8.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say World"
          command: "echo World!"
  print-my-name:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say My name"
          command: echo $PIPELINE_CREATOR
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-world-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
  printing-myname-workflow:
    jobs:
      - print-my-name